site_name: Nixware Lua API
nav:
    - Home: index.md
    - ui:
      - ui: ui/ui.md
      - vars: ui/vars.md
      - types:
        - check_box_t: ui/types/check_box_t.md
        - color_edit_t: ui/types/color_edit_t.md
        - combo_box_t: ui/types/combo_box_t.md
        - multi_combo_box_t: ui/types/multi_combo_box_t.md
        - key_bind_t: ui/types/key_bind_t.md
        - slider_float_t: ui/types/slider_float_t.md
        - slider_int_t: ui/types/slider_int_t.md
        - text_input_t: ui/types/text_input_t.md
    - client: client.md
    - renderer: renderer.md
    - ragebot: ragebot.md
    - types:
      - vec2_t: types/vec2_t.md
      - vec3_t: types/vec3_t.md
      - angle_t: types/angle_t.md
      - rect_t: types/rect_t.md
      - color_t: types/color_t.md
    - source engine:
      - types:
        - game_event_t: sourceengine/types/game_event_t.md
        - usercmd_t: sourceengine/types/usercmd_t.md
        - convar_t: sourceengine/types/convar_t.md
        - entity_t: sourceengine/types/entity_t.md
        - player_info_t: sourceengine/types/player_info_t.md
        - trace_t: sourceengine/types/trace_t.md
        - shot_info_t: sourceengine/types/shot_info_t.md
      - se: sourceengine/se.md
      - engine: sourceengine/engine.md
      - trace: sourceengine/trace.md
      - entitylist: sourceengine/entitylist.md
      - globalvars: sourceengine/globalvars.md
      - clientstate: sourceengine/clientstate.md
    - callbacks: callbacks.md
theme:
  logo: https://nixware.cc/styles/default/xenforo/ava.png
  name: material
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition